---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86159.
--- DateTime: 2024-11-13 13:21
---
-- 订单id
local voucherId = ARGV[1]
-- 用户id
local userId = ARGV[2]
-- 订单id
local orderId = ARGV[3]
-- 优惠券key
local stockKey = 'seckill:stock:' .. voucherId
-- 订单key
local orderKey = 'seckill:order:' .. voucherId

-- 判断库存是否充足，确保将库存值转为数字类型进行比较
local stock = tonumber(redis.call('get', stockKey))
if stock == nil or stock <= 0 then
    return 1
end

-- 判断用户是否下单，sismember 用于检查 Redis 集合中是否包含某个元素
if redis.call('sismember', orderKey, userId) == 1 then
    return 2
end

-- 扣减库存
redis.call('incrby', stockKey, -1)

-- 将userId存入当前优惠券的set集合
redis.call('sadd', orderKey, userId)

-- 发送消息到队列中 XADD stream.orders * k1 v1 k2 v2...
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0
